package com.tudai.terceraentrega.config;
import com.tudai.terceraentrega.entities.*; import com.tudai.terceraentrega.repository.*; import org.springframework.boot.CommandLineRunner; import org.springframework.core.io.ClassPathResource; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional; import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*;
@Component
public class CsvDataLoader implements CommandLineRunner {
 private final CarreraRepository carreras; private final EstudianteRepository estudiantes; private final InscripcionRepository inscripciones;
 public CsvDataLoader(CarreraRepository c,EstudianteRepository e,InscripcionRepository i){carreras=c;estudiantes=e;inscripciones=i;}
 @Override @Transactional public void run(String... args) throws Exception { if(carreras.count()>0)return; cargarCarreras();cargarEstudiantes();cargarInscripciones();System.out.println("CSV del ejercicio integrador cargados correctamente."); }
 private List<String> lineas(String p)throws IOException{try(var in=new ClassPathResource(p).getInputStream();var br=new BufferedReader(new InputStreamReader(in,StandardCharsets.ISO_8859_1))){return br.lines().toList();}}
 private void cargarCarreras()throws IOException{var l=lineas("data/carreras.csv");for(int i=1;i<l.size();i++){if(l.get(i).isBlank())continue;String[]x=l.get(i).split(",",-1);Carrera c=new Carrera();c.setIdCarrera(Integer.parseInt(x[0].trim()));c.setNombre(x[1].trim());c.setDuracion(Integer.parseInt(x[2].trim()));carreras.save(c);}}
 private Genero g(String s){String n=s.trim().toUpperCase();return switch(n){case"MALE","MASCULINO"->Genero.MASCULINO;case"FEMALE","FEMENINO"->Genero.FEMENINO;default->Genero.OTRO;};}
 private void cargarEstudiantes()throws IOException{var l=lineas("data/estudiantes.csv");for(int i=1;i<l.size();i++){if(l.get(i).isBlank())continue;String[]x=l.get(i).split(",",-1);Estudiante e=new Estudiante();e.setIdEstudiante(Integer.parseInt(x[0].trim()));e.setNumeroDocumento(x[0].trim());e.setNombres(x[1].trim());e.setApellido(x[2].trim());e.setEdad(Integer.parseInt(x[3].trim()));e.setGenero(g(x[4]));e.setCiudadResidencia(x[5].trim());e.setNumeroLibretaUniversitaria(x[6].trim());estudiantes.save(e);}}
 private void cargarInscripciones()throws IOException{var l=lineas("data/estudianteCarrera.csv");for(int i=1;i<l.size();i++){if(l.get(i).isBlank())continue;String[]x=l.get(i).split(",",-1);int e=Integer.parseInt(x[1].trim()),c=Integer.parseInt(x[2].trim());InscripcionId id=new InscripcionId(e,c);if(inscripciones.existsById(id))continue;var est=estudiantes.findById(e).orElse(null);var car=carreras.findById(c).orElse(null);if(est==null||car==null)continue;int ai=Integer.parseInt(x[3].trim());int ge=Integer.parseInt(x[4].trim());inscripciones.save(new Inscripcion(est,car,ai,ge==0?null:ge));}}
}
